// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7SB5E6Al3ih5FOAV0IczTVE6cCITNVk',
    appId: '1:23413611872:web:bda21d6fce114124abd205',
    messagingSenderId: '23413611872',
    projectId: 'expense-tracker-89b59',
    authDomain: 'expense-tracker-89b59.firebaseapp.com',
    storageBucket: 'expense-tracker-89b59.firebasestorage.app',
    measurementId: 'G-BNCNV6G7GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd9Guay_hDe9ZYUzmTgwba2GZJpLOQvCE',
    appId: '1:23413611872:android:2a454ff6c28b20beabd205',
    messagingSenderId: '23413611872',
    projectId: 'expense-tracker-89b59',
    storageBucket: 'expense-tracker-89b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8cKbP3S8Dx1xGS8XgR4hIgq3bj_C5nJA',
    appId: '1:23413611872:ios:b1bb320e7999587eabd205',
    messagingSenderId: '23413611872',
    projectId: 'expense-tracker-89b59',
    storageBucket: 'expense-tracker-89b59.firebasestorage.app',
    iosBundleId: 'com.example.expenseHandler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7SB5E6Al3ih5FOAV0IczTVE6cCITNVk',
    appId: '1:23413611872:web:85dd22ae83d441f9abd205',
    messagingSenderId: '23413611872',
    projectId: 'expense-tracker-89b59',
    authDomain: 'expense-tracker-89b59.firebaseapp.com',
    storageBucket: 'expense-tracker-89b59.firebasestorage.app',
    measurementId: 'G-MPXLLRM4KK',
  );
}
